description = "mplain"
audio_length = 53.320
text_length = 107

[arguments]
audio = "001m.mp3"
text = "001m.mplain.txt"
config = "task_language=eng|is_text_type=mplain|os_task_file_format=json"
rconf = ""

[execution]
warmup_runs = 0
timed_runs = 8

