description = "mplain"
audio_length = 3613.700
text_length = 8391

[arguments]
audio = "060m.mp3"
text = "060m.mplain.txt"
config = "task_language=eng|is_text_type=mplain|os_task_file_format=json"
rconf = ""

[execution]
warmup_runs = 0
timed_runs = 2

