description = "plain, sentence, no C extensions"
audio_length = 53.320
text_length = 15

[arguments]
audio = "001m.mp3"
text = "001m.plain.sentence.txt"
config = "task_language=eng|is_text_type=plain|os_task_file_format=json"
rconf = "c_extensions=False"

[execution]
warmup_runs = 1
timed_runs = 8

