description = "plain, sentence"
audio_length = 614.45
text_length = 84 

[arguments]
audio = "010m.mp3"
text = "010m.plain.sentence.txt"
config = "task_language=eng|is_text_type=plain|os_task_file_format=json"
rconf = ""

[execution]
warmup_runs = 0
timed_runs = 8

