description = "plain, sentence"
audio_length = 320.91
text_length = 84

[arguments]
audio = "005m.mp3"
text = "005m.plain.sentence.txt"
config = "task_language=eng|is_text_type=plain|os_task_file_format=json"
rconf = ""

[execution]
warmup_runs = 1
timed_runs = 16

